### PR TITLE
Create easteregg.txt

### PR DESCRIPTION
**Pull request by HahaYes-dev**
Please accept this extremely pog cookie that took me 3 hours to make. Please use this as a easter egg.

### CODE REVIEW

**Comment by cursorweb** [comment]
if you could add some way we could integrate this I'll consider it

**Comment by HahaYes-dev** [comment]
Yeah, I can integrate this. It would involve a keyword and I would have to like make it go boop

**Comment by firefish111** [comment]
Honestly?! Why are you imposing easter eggs on every tom dick and harry @HahaYes-dev

**Comment by HahaYes-dev** [comment]
> Honestly?! Why are you imposing easter eggs on every tom dick and harry @HahaYes-dev

Can you stop stalking me k thanks bai

**Comment by JDOG787** [comment]
Lol @HahaYes-dev

**Comment by firefish111** [comment]
@HahaYes-dev I follow you, I can't not see every pull request you make

**Comment by cursorweb** [comment]
ok then closing this thread

**Comment by firefish111** [comment]
@cursorweb ~~don't accept this, it'll just encourage him~~

**Pull request closed without merging**
